import { InteractionEvent } from "./types";

export const SEED_EVENTS: InteractionEvent[] = [
  {
    id: "ev_10",
    clientId: "c_tsai",
    clientName: "蔡佩芬",
    type: "REPORT",
    title: "生成保障缺口報告",
    description: "建議書已產出，主要針對重大疾病一次金加強，建議額度 100 萬以上。",
    timestamp: "2026-05-14T09:15:00Z",
  },
  {
    id: "ev_11",
    clientId: "c_lo",
    clientName: "羅德華",
    type: "SPIN",
    title: "SPIN 訪談進行中",
    description: "已完成情況階段，正在深入問題性問題，聚焦企業主失能風險。",
    timestamp: "2026-05-14T16:00:00Z",
  },
  {
    id: "ev_1",
    clientId: "c_wang",
    clientName: "王大明",
    type: "SPIN",
    title: "SPIN 對話完成 — 王大明",
    description: "已整理 8 筆洞察，完成 4 個階段切換。主要缺口：醫療實支實付 + 失能收入保障。",
    timestamp: "2026-05-13T11:50:00Z",
    metadata: { sessionId: "spin_demo_wang" },
  },
  {
    id: "ev_2",
    clientId: "c_wang",
    clientName: "王大明",
    type: "REPORT",
    title: "生成保障缺口報告",
    description: "根據 SPIN 對話自動生成，含現狀分析、風險缺口、建議方案三個區塊。",
    timestamp: "2026-05-13T12:00:00Z",
  },
  {
    id: "ev_3",
    clientId: "c_lin",
    clientName: "林建華",
    type: "SPIN",
    title: "SPIN 對話完成 — 林建華",
    description: "已整理 8 筆洞察，完成 4 個階段切換。主要缺口：遺產稅規劃 + 長照費用缺口。",
    timestamp: "2026-05-11T15:00:00Z",
    metadata: { sessionId: "spin_demo_lin" },
  },
  {
    id: "ev_4",
    clientId: "c_lo",
    clientName: "羅德華",
    type: "THEATER",
    title: "劇場演練：處理反對意見",
    description: "與 AI 客戶進行「疑慮型」人格對話演練，獲得 8.5 分，建議加強 Need-Payoff 引導。",
    timestamp: "2026-05-10T16:20:00Z",
  },
  {
    id: "ev_5",
    clientId: "c_wang",
    clientName: "王大明",
    type: "SHARE_OPEN",
    title: "客戶開啟分享報告",
    description: "王大明 於 15:30 檢視了保障缺口分析報告，停留時間約 8 分鐘。",
    timestamp: "2026-05-09T15:30:00Z",
  },
  {
    id: "ev_6",
    clientId: "c_chen",
    clientName: "陳雅婷",
    type: "SPIN",
    title: "開始新 SPIN 對話",
    description: "初步釐清自由工作者的意外風險需求，已完成情況階段。",
    timestamp: "2026-05-08T14:00:00Z",
  },
  {
    id: "ev_7",
    clientId: "c_lin",
    clientName: "林建華",
    type: "SYSTEM",
    title: "新增客戶資料",
    description: "從 Excel 匯入成功，已建立完整客戶輪廓。",
    timestamp: "2026-05-01T11:00:00Z",
  },
];
