import { Client, ClientComplianceChecklist, DEFAULT_CLIENT_COMPLIANCE } from "./types";

const COMPLETE_CLIENT_COMPLIANCE: ClientComplianceChecklist = {
  kycStatus: "COMPLETE",
  suitabilityStatus: "PARTIAL",
  consentStatus: "COMPLETE",
  missingItems: ["補齊保障缺口確認"],
};

const RAW_SEED_CLIENTS: Array<Omit<Client, "complianceChecklist" | "sensitivityLevel" | "kycStatus">> = [
  {
    id: "c_wang",
    name: "王大明",
    email: "ta-ming.wang@email.com",
    phone: "0912-345-678",
    birthDate: "1985-03-12",
    occupation: "科技業中階主管",
    annualIncome: 1800000,
    family: [
      { id: "f1", relation: "配偶", name: "林小美", age: 38 },
      { id: "f2", relation: "子", name: "王小明", age: 8 },
      { id: "f3", relation: "女", name: "王小美", age: 5 },
    ],
    existingPolicies: [
      { id: "p1", type: "定期壽險", amount: 5000000, provider: "國泰人壽" },
      { id: "p2", type: "住院醫療", amount: 2000, provider: "富邦人壽" },
    ],
    tags: ["高意向", "雙薪家庭"],
    aiTags: ["子女教育金缺口", "醫療險不足"],
    status: "ACTIVE",
    lastInteraction: "2026-05-13T10:00:00Z",
  },
  {
    id: "c_lin",
    name: "林建華",
    email: "ch.lin@email.com",
    phone: "0922-111-222",
    birthDate: "1972-11-25",
    occupation: "中小企業主",
    annualIncome: 5000000,
    family: [
      { id: "f4", relation: "配偶", name: "張麗華", age: 50 },
    ],
    existingPolicies: [
      { id: "p3", type: "終身壽險", amount: 10000000, provider: "南山人壽" },
    ],
    tags: ["保守型", "退休規劃"],
    aiTags: ["遺產稅問題", "長期照護缺口"],
    status: "ACTIVE",
    lastInteraction: "2026-04-18T15:30:00Z",
  },
  {
    id: "c_chen",
    name: "陳雅婷",
    email: "yating.chen@email.com",
    phone: "0933-999-888",
    birthDate: "1994-07-08",
    occupation: "自由設計師",
    annualIncome: 900000,
    family: [],
    existingPolicies: [],
    tags: ["疑慮型", "單身"],
    aiTags: ["意外險建議", "實支實付醫療"],
    status: "PROSPECT",
    lastInteraction: "2026-05-10T14:00:00Z",
  },
  {
    id: "c_lee",
    name: "李國樑",
    email: "gl.lee@email.com",
    phone: "0988-777-666",
    birthDate: "1980-01-30",
    occupation: "公務員",
    annualIncome: 1200000,
    family: [
      { id: "f5", relation: "配偶", name: "黃芳芬", age: 44 },
      { id: "f6", relation: "子", name: "李小寶", age: 12 },
    ],
    existingPolicies: [
      { id: "p4", type: "防癌險", amount: 1000000, provider: "新光人壽" },
    ],
    tags: ["穩健型", "教育基金"],
    aiTags: ["重大傷病缺口"],
    status: "ACTIVE",
    lastInteraction: "2026-04-15T14:00:00Z",
  },
  {
    id: "c_wu",
    name: "吳美玲",
    email: "meiling.wu@email.com",
    phone: "0977-555-444",
    birthDate: "1965-05-15",
    occupation: "退休教師",
    annualIncome: 800000,
    family: [],
    existingPolicies: [
      { id: "p5", type: "養老險", amount: 2000000, provider: "三商美邦" },
    ],
    tags: ["安養規劃", "長照關注"],
    aiTags: ["失能保障強化"],
    status: "ACTIVE",
    lastInteraction: "2026-04-10T11:20:00Z",
  },
  {
    id: "c_chang",
    name: "張志明",
    email: "cm.chang@email.com",
    phone: "0966-333-222",
    birthDate: "1998-10-12",
    occupation: "外送員",
    annualIncome: 500000,
    family: [],
    existingPolicies: [],
    tags: ["高風險業", "預算受限"],
    aiTags: ["意外險急需", "簡易醫療保障"],
    status: "PROSPECT",
    lastInteraction: "2026-05-12T09:00:00Z",
  },
  {
    id: "c_huang",
    name: "黃曉燕",
    email: "hy.huang@email.com",
    phone: "0955-111-000",
    birthDate: "1988-12-01",
    occupation: "銀行行員",
    annualIncome: 1100000,
    family: [
      { id: "f7", relation: "父", name: "黃老伯", age: 70 },
    ],
    existingPolicies: [
      { id: "p6", type: "投資型保單", amount: 3000000, provider: "安聯人壽" },
    ],
    tags: ["孝親需求", "理財導向"],
    aiTags: ["長輩醫療負擔分析"],
    status: "ACTIVE",
    lastInteraction: "2026-04-21T13:30:00Z",
  },
  {
    id: "c_chu",
    name: "朱大山",
    email: "ts.chu@email.com",
    phone: "0944-888-777",
    birthDate: "1978-02-14",
    occupation: "大車司機",
    annualIncome: 1500000,
    family: [
      { id: "f8", relation: "配偶", name: "沈小姐", age: 40 },
    ],
    existingPolicies: [],
    tags: ["高壓職業", "遲疑型"],
    aiTags: ["家庭支柱失能風險"],
    status: "PROSPECT",
    lastInteraction: "2026-04-19T17:10:00Z",
  },
  {
    id: "c_tsai",
    name: "蔡佩芬",
    email: "pf.tsai@email.com",
    phone: "0999-000-111",
    birthDate: "1991-09-30",
    occupation: "護理師",
    annualIncome: 1300000,
    family: [],
    existingPolicies: [
      { id: "p7", type: "實支實付", amount: 150000, provider: "台灣人壽" },
    ],
    tags: ["醫療背景", "高保障要求"],
    aiTags: ["重大疾病一次金加強"],
    status: "ACTIVE",
    lastInteraction: "2026-05-14T08:00:00Z",
  },
  {
    id: "c_lo",
    name: "羅德華",
    email: "th.lo@email.com",
    phone: "0900-222-333",
    birthDate: "1982-06-21",
    occupation: "餐廳老闆",
    annualIncome: 2500000,
    family: [
      { id: "f9", relation: "配偶", name: "王太太", age: 40 },
      { id: "f10", relation: "子", name: "羅小弟", age: 10 },
      { id: "f11", relation: "子", name: "羅小二", age: 7 },
    ],
    existingPolicies: [],
    tags: ["創業者", "資產傳承"],
    aiTags: ["企業關鍵人保險", "子女教育金規劃"],
    status: "PROSPECT",
    lastInteraction: "2026-04-17T11:45:00Z",
  },
];

export const SEED_CLIENTS: Client[] = RAW_SEED_CLIENTS.map((client) => {
  const complianceChecklist =
    client.existingPolicies.length > 0
      ? COMPLETE_CLIENT_COMPLIANCE
      : DEFAULT_CLIENT_COMPLIANCE;

  return {
    ...client,
    complianceChecklist,
    sensitivityLevel: "NORMAL",
    kycStatus: complianceChecklist.kycStatus,
  };
});
